INSERT INTO skills (name, description)
VALUES
    ('Java', 'Uma linguagem de programação orientada a objetos popular.'),
    ('Python', 'Uma linguagem de programação versátil e fácil de ler.'),
    ('JavaScript', 'Uma linguagem de script dinâmica para desenvolvimento web do lado do cliente.'),
    ('C++', 'Uma linguagem poderosa usada para programação em nível de sistema.'),
    ('C#', 'Uma linguagem para construir aplicativos e jogos para Windows.'),
    ('Ruby', 'Uma linguagem simples e elegante frequentemente usada para desenvolvimento web.'),
    ('Swift', 'A linguagem da Apple para construir aplicativos iOS e macOS.'),
    ('PHP', 'Uma linguagem para desenvolvimento web no lado do servidor.'),
    ('TypeScript', 'Uma linguagem de programação que estende o JavaScript com recursos de tipagem estática.'),
    ('Kotlin', 'Uma linguagem moderna para desenvolvimento Android com interoperabilidade com Java.'),
    ('SQL', 'Linguagem para manipulação de bancos de dados relacionais.'),
    ('HTML', 'Linguagem de marcação para criação de páginas web.'),
    ('CSS', 'Linguagem de estilo para definir a aparência das páginas web.'),
    ('React', 'Uma biblioteca JavaScript para criar interfaces de usuário interativas.'),
    ('Angular', 'Um framework JavaScript para construir aplicativos web complexos.'),
    ('Vue.js', 'Uma estrutura progressiva para a construção de interfaces de usuário.'),
    ('Node.js', 'Um ambiente de tempo de execução JavaScript para construção de aplicações de rede escaláveis.'),
    ('Spring Boot', 'Um framework para construção de aplicativos Java com configuração mínima.'),
    ('Django', 'Um framework web em Python para desenvolvimento rápido e limpo.'),
    ('Git', 'Um sistema de controle de versão distribuído para rastrear mudanças em código-fonte.'),
    ('PostgreSQL', 'Um sistema de gerenciamento de banco de dados relacional de código aberto.'),
    ('MySQL', 'Um sistema de gerenciamento de banco de dados relacional de código aberto.'),
    ('AWS', 'Amazon Web Services, uma plataforma de serviços de computação em nuvem.'),
    ('Azure', 'Microsoft Azure, uma plataforma de computação em nuvem da Microsoft.'),
    ('Google Cloud', 'Plataforma de computação em nuvem do Google.'),
    ('Kanban', 'Um método ágil de gerenciamento de projetos e fluxo de trabalho.'),
    ('Lean', 'Uma abordagem para otimização de processos e redução de desperdícios.'),
    ('RESTful API', 'Uma API que adere aos princípios de REST (Representational State Transfer).'),
    ('OAuth', 'Um protocolo de autorização para autenticação de usuários e permissão de acesso a recursos.'),
    ('JWT', 'JSON Web Token, um padrão aberto para representar informações seguras entre duas partes.')
;
